AWSTemplateFormatVersion: 2010-09-09
Description: "A simple traditional app to demonstrate an end-to-end developer experience using Cloud One Conformity"
Metadata:
  License: MIT-License
Resources:
  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: End2EndKeyPair
      ImageId: ami-013a129d325529d4d
      InstanceType: c6g.medium
      IamInstanceProfile: !Ref iamInstanceProfile
      Monitoring: true
      SecurityGroups:
        - !Ref "securityGroup"
      Tags:
        - Key: Environment
          Value: staging
        - Key: Role
          Value: Demo
        - Key: Owner
          Value: atiradocc
        - Key: Name
          Value: End2EndEC2Instance
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2 Instance Security Group
      GroupDescription: Enable access admin access to this instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: "Access to SSH"
      Tags:
        - Key: Environment
          Value: staging
        - Key: Role
          Value: read-only
        - Key: Owner
          Value: atiradocc
        - Key: Name
          Value: End2EndSG
  iamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref "iamRole"
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Tags:
        - Key: Environment
          Value: staging
        - Key: Role
          Value: read-only
        - Key: Owner
          Value: atiradocc
        - Key: Name
          Value: End2EndiamRole
  iamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ListS3Buckets
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: "s3:List*"
            Resource: "*"
      Roles:
        - !Ref "iamRole"
