AWSTemplateFormatVersion: 2010-09-09
Description: "A ''traditional'' application to demonstrate an end-to-end developer experience using Cloud One Conformity"
Metadata:
  License: MIT-License
Resources:
  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: End2EndKeyPair
      ImageId: ami-0d6621c01e8c2de2c
      InstanceType: t2.nano
      SecurityGroups:
        - !Ref "securityGroup"
      Tags:
        - Key: Environment
          Value: staging
        - Key: Role
          Value: Demo
        - Key: Owner
          Value: atiradocc
        - Key: Name
          Value: End2EndEC2Instance
  securityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2 Instance Security Group
      GroupDescription: Enable access admin and data access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: "Access to SSH"
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0
          Description: "Access to RDP"
      Tags:
        - Key: Environment
          Value: staging
        - Key: Role
          Value: read-only
        - Key: Owner
          Value: atiradocc
        - Key: Name
          Value: End2EndSG
