name: DevOps Pipeline with CloudOne Conformity Pipeline Scanner
on: 
  push:
    branches: 
      - master
jobs:      
    ScanAndDeployTemplates:
      runs-on: ubuntu-latest
      steps:
        - name: Check out code for the Pipeline Scanner
          uses: actions/checkout@v2
        - name: Scan CloudFormation templates
          uses: raphabot/conformity-template-scanner-pipeline@v1.0.0
          env:
            cc_apikey: ${{ secrets.cc_apikey }}
            cc_region: us-west-2
            templatePath: simpleEC2Instance.template.yaml
            maxExtreme: 0
            maxVeryHigh: 0
            maxHigh: 0
            maxMedium: 0
        - name: Set up the CLI to deploy the template
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2
        - name: Deploy the template
          run: |
            aws cloudformation create-stack --stack-name simpleEC2Instance --template-body file://simpleEC2Instance.template.yaml --capabilities CAPABILITY_NAMED_IAM 
